config/routes.rb
Rails.application.routes.draw do

  root 'users#index'
  resources :users

  match 'password_reset'  =>  'password_resets#new',  via: [:get],  :as => "new_password_reset"
  match 'password_reset'  =>  'password_resets#create',  via: [:post]
  match 'password_reset/:reset/edit'  =>  'password_resets#edit',  via: [:get], as: "edit_password_reset"
  match 'password_reset/:reset/edit'  =>  'password_resets#update',  via: [:patch]

  match 'login'  =>  'sessions#new',  via: [:get],  :as => "login"
  match 'login'  =>  'sessions#create',  via: [:post]
  match 'logout'  =>  'sessions#destroy',  via: [:delete], :as => "logout"

  match '/account_activations/:activation_token/edit'  =>  'account_activations#edit',  via: [:get],  :as => "edit_account_activation"

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:password_reset][:email])
    user.send_password_reset if user
    flash[:info] = "Email sent with password reset instructions"
    redirect_to root_url
  end

  def edit
    @user = User.find_by!(password_reset_token: params[:reset])
  end

  def update
    @user = User.find_by!(password_reset_token: params[:reset])
    if @user.password_reset_sent_at < 2.hours.ago
      redirect_to new_password_reset_path, alert: "Password reset has expired"
    elsif @user.update_attributes(user_params)
      redirect_to root_url, notice: "Password has been reset"
    else
      render 'edit'
    end
  end

  private

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end

end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<h1>Reset Password</h1>

<div class="row">
  <div class="col-md-12">
    <%= form_for(@user, url: edit_password_reset_path(params[:reset])) do |f| %>
      <% if @user.errors.any? %>
        <div id="error_explanation">
          <div class="alert alert-danger">
            The form contains <%= pluralize(@user.errors.count, "error") %>.
          </div>
          <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>


      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Update Password", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/password_resets/new.html.erb
<h1>Log in</h1>

<div class="row">
  <div class="col-md-12">
    <%= form_for(:password_reset, url: password_reset_path) do |f| %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.submit "Reset Password", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>