config/routes.rb
Rails.application.routes.draw do

  root 'users#index'
  resources :users

  match 'password_reset'  =>  'password_resets#new',  via: [:get],  :as => "new_password_reset"
  match 'password_reset'  =>  'password_resets#create',  via: [:post]
  match 'password_reset/:reset/edit'  =>  'password_resets#edit',  via: [:get], as: "edit_password_reset"
  match 'password_reset/:reset/edit'  =>  'password_resets#update',  via: [:patch]

  match 'login'  =>  'sessions#new',  via: [:get],  :as => "login"
  match 'login'  =>  'sessions#create',  via: [:post]
  match 'logout'  =>  'sessions#destroy',  via: [:delete], :as => "logout"

  match '/account_activations/:activation_token/edit'  =>  'account_activations#edit',  via: [:get],  :as => "edit_account_activation"

end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to "Userauth", root_path, class: "navbar-brand" %>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="<%#= is_active?('/welcome/about') %>">
                        <%= link_to "About", root_path %>
                    </li>
                    <li class="<%#= is_active?('/welcome/services') %>">
                        <%= link_to "Services", root_path %>
                    </li>
                    <li class="<%#= is_active?('/listings') %>">
                        <%= link_to "Listings", root_path %>
                    </li>
                    <li class="<%#= is_active?('/posts') %>">
                        <%= link_to "Blog", root_path %>
                    </li>
                    <% if !current_user %>
                        <li class="<%#= is_active?('/welcome/bloghome2') %>">
                            <%= link_to "Sign up", new_user_path %>
                        </li>
                        <li class="<%#= is_active?('/welcome/bloghome2') %>">
                            <%= link_to "Login", login_path %>
                        </li>
                    <% else %>
                        <li class="<%#= is_active?('/welcome/bloghome2') %>">
                            <%= link_to "Log out", logout_path, method: "delete" %>
                        </li>
                    <% end %>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Userauth</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render "layouts/nav" %>

      <% flash.each do |message_type, message| %>
        <% if message_type == "notice" %>
          <div class="alert alert-success"><%= message %><button class="close" data-dismiss="alert">×</button></div>
        <% elsif message_type == "alert" %>
          <div class="alert alert-danger"><%= message %><button class="close" data-dismiss="alert">×</button></div>
        <% else %>
          <div class="alert alert-<%= message_type %>"><%= message %><button class="close" data-dismiss="alert">×</button></div>
        <% end %>
      <% end %>

      <%= yield %>
      
    </div>
  </body>
</html>